# Generated by Django 4.0.2 on 2022-02-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Category', models.CharField(choices=[('FS', 'FullStack'), ('AWS', 'DevOps'), ('DS', 'DataScience')], default='FullStack', max_length=3)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
