# Generated by Django 4.0.2 on 2022-02-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
