# Generated by Django 4.0.2 on 2022-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_blog_date_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(default='django.png', upload_to='img/'),
        ),
    ]
