# Generated by Django 4.0.2 on 2022-02-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_update']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_stamp']},
        ),
    ]
