# Generated by Django 4.0.2 on 2022-02-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blog_likes_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
